### ISSUE TITLE
[Bug] wordlist with number 

### ISSUE THREAD

**Issue by Anyon3** [d4rkcat/dnsbrute#2]
Hi,

```
Traceback (most recent call last):
  File "/bin/dnsbrute", line 180, in <module>
    writeout("good")
  File "/bin/dnsbrute", line 40, in __exit__
    seconds = int(time.strftime('%S', time.gmtime(taken)))
NameError: global name 'taken' is not defined
```

With subdomainbig.txt (~50k) np with subdomain.txt (~2K)

Thanks for your sharing btw

**Comment by Anyon3** [comment]
It's working today, don't know how to reproduice it, maybe the update of some python dependencies fixed this problem, if someone know which one, please, share

**Comment by Anyon3** [comment]
This script is under rated and better than most of the same kind of "dns by bruteforce" you could find on github.
